### ISSUE TITLE
Use `noMoreWidget` instead of `noMoreText` and `noMoreTextStyle`

### ISSUE THREAD

**Issue by Hamza5** [shareven/refresh_loadmore#2]
Hello,

I wanted to use this widget, but what stopped me is that this widget limits me to use text when no more content is available, which is really inconvenient for a lot of apps. So I want to propose to replace the parameters `noMoreText` and `noMoreTextStyle` with a generic `noMoreWidget` which accepts any widget. This way it will fit any application in any context.

Thanks.

**Comment by shareven** [comment]
Thank you !  Now you can use `noMoreWidget` on version: 2.0.4
